name: Schedule Discord Bot

on:
    schedule:
        - cron: "0 17 * * 0" # Every Sunday at 10:00 AM Arizona time (5:00 PM UTC)
    branches:
        - main

jobs:
    run-bot:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20.14.0" # or the version you're using

            - name: Install dependencies
              run: npm install

            - name: Run bot script
              env:
                  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
              run: node bot.js # Replace with the entry point of your bot
